Update example for 1.12 (#111)
* update for 1.12

* Update android dependencies

* Update build

* Update podfile

* Bitrise only work on 1.12.13+hotfix.6

* Update pubspec, changelog

* update build machine

diff --git a/bitrise.yml b/bitrise.yml
--- a/bitrise.yml
+++ b/bitrise.yml
@@ -3,47 +3,44 @@ format_version: '8'
 default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git
 project_type: flutter
 trigger_map:
-  - push_branch: master
-    workflow: primary
-  - pull_request_source_branch: "*"
-    workflow: primary
+- push_branch: master
+  workflow: primary
+- pull_request_source_branch: "*"
+  workflow: primary
 workflows:
   primary:
     steps:
-      - git-clone@4.0.17: {}
-      - cache-pull@2.1.1: {}
-      - flutter-installer: {}
-      - flutter@0.0.7:
-          inputs:
-            - commands: packages get|analyze
-            - version: 1.9.1+hotfix.4
-      - script@1.1.5:
-          inputs:
-            - content: |-
-                #!/usr/bin/env bash
-                # fail if any commands fails
-                set -e
-                # debug log
-                set -x
+    - git-clone@4.0.17: {}
+    - cache-pull@2.1.3: {}
+    - flutter-installer: {}
+    - flutter@0.0.8:
+        inputs:
+        - commands: packages get|analyze
+        - version: 1.12.13+hotfix.6
+    - script@1.1.5:
+        inputs:
+        - content: |-
+            #!/usr/bin/env bash
+            # fail if any commands fails
+            set -e
+            # debug log
+            set -x
 
-                cd example
-                flutter build ios --debug --no-codesign
-                flutter build apk --debug
-      - cache-push@2.2.1: {}
-    meta:
-      bitrise.io:
-        stack: osx-xcode-11.1.x
+            cd example
+            flutter build ios --debug --no-codesign
+            flutter build apk --debug
+    - cache-push@2.2.3: {}
 app:
   envs:
-    - opts:
-        is_expand: false
-      BITRISE_FLUTTER_PROJECT_LOCATION: example
-    - opts:
-        is_expand: false
-      BITRISE_PROJECT_PATH: example/ios/Runner.xcworkspace
-    - opts:
-        is_expand: false
-      BITRISE_SCHEME: Runner
-    - opts:
-        is_expand: false
-      BITRISE_EXPORT_METHOD: development
+  - opts:
+      is_expand: false
+    BITRISE_FLUTTER_PROJECT_LOCATION: example
+  - opts:
+      is_expand: false
+    BITRISE_PROJECT_PATH: example/ios/Runner.xcworkspace
+  - opts:
+      is_expand: false
+    BITRISE_SCHEME: Runner
+  - opts:
+      is_expand: false
+    BITRISE_EXPORT_METHOD: development
